spring:
  datasource:
    url: jdbc:h2:mem:db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yaml
    enabled: true

springdoc:
  api-docs:
    path: /schema
  swagger-ui:
    urls:
      - todos.yaml
    path: /

logging:
  level:
    root: info
